### ISSUE TITLE
Intégration dans l'architecture de georchestra version 16.12

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/photos_obliques#1]
Intégration du module photo oblique  dans l'architecture de Rennes Métropole prévue sur la version 16.12 de geOrchestra.
Ticket destiné à des échanges techniques préliminaires.

**Comment by catmorales** [comment]
De camptocamp /intégration du module :

> Vos serveurs sont actuellement en debian 7, avec des tomcat 6.
> 
> A la prochaine mise à jour vers geOrchestra 16.12, il faudra instancier de nouveaux serveurs, car tomcat 6 n'est plus supporté.
> 
> Du coup, on partira sur une installation complète à partir de zéro sur de nouveaux serveurs.
> Le déploiement des webapps devra être revu, car le module server-deploy sera déprécié pour la 16.12 (plus de mainteneur, fonctionnement old-school, etc ...)
> Nous avons acquis une expérience très confortable désormais avec Docker, et il serait dommage de ne pas en profiter dans cette situation.
> Dans les images docker, nous n'utilisons pas tomcat (trop lourd) mais jetty, en version 9.
> Du coup, il faudrait simplement demander à votre prestataire de fournir une image docker (et ses sources) contenant son application, avec son mode d'emploi. C'est un mode de fonctionnement extrêmement propre et convenable pour nous.

**Comment by catmorales** [comment]
@Gaetanbru va commencer les dev sur ce module et me demande pour son intégration sur notre Plateforme, "l'URL  qui sera utilisée  pour l'accès aux données, côté Apache" . 

@fvanderbiest , je ne me souviens pas très bien de ce que nous avions dit mais il me semble que ce sera quelque chose du genre : https://portail.sig.rennesmetropole.fr/photos_obliques. Me le confirmes tu ?

**Comment by fvanderbiest** [comment]
Qu'est ce que ça veut dire "l'URL qui sera utilisée pour l'accès aux données, côté Apache" ?
Je ne saisis pas bien. Le mieux est probablement que Gaetan m'appelle directement au 04 58 48 20 33

**Comment by Gaetanbru** [comment]
Bonjour, on souhaiterai les informations pour mettre en cohérence les URL d'appel avec le système de fichier. Notamment pour obtenir les images à charger dans les fenêtres de l'addon. Je peux t'appeler dans quelques minutes. Merci.

**Comment by fvanderbiest** [comment]
ok

**Comment by Gaetanbru** [comment]
@catmorales nous attendons votre retour pour avoir plus d'informations sur ce point.

**Comment by MaelREBOUX** [comment]
Bonjour, concernant les url d'accès aux ressources tout est décrit dans les chapitres 2.1 et 3.4 de nos spécifications.

La colonne répertoire = le noms des répertoires sur le système de fichiers accessibles soit par apache soit par la webapp Java.
La colonne url = l'url

![screenshot343](https://cloud.githubusercontent.com/assets/6370443/20011843/3d4f6d96-a2ad-11e6-86f2-c8940108e646.png)

@Gaetanbru quel est le souci ?

**Comment by Gaetanbru** [comment]
Bonjour,

Merci pour la structure présente dans les spécifications, on se base donc sur le tableau mais pour optimiser les temps de réponse  devra t'on s'attendre à un système particulier de  nommage de fichier (a partir du nom système par exemple) avec une arborescence de dossier permettant de trouver plus rapidement les photos dans le répertoire de stockage ?

Sinon nous prenons le nom des fichiers tels que fourni avec l'URL précisé en 3.4 des spécifications.
—
Gfi Informatique
Gaëtan Bruel
gaetan.bruel@gfi.fr
—
11 rue Louis de Broglie - - 22300 LANNION
Standard. : +33 (0)2 96 48 25 67


________________________________
De : Maël REBOUX <notifications@github.com>
Envoyé : vendredi 4 novembre 2016 16:40:23
À : sigrennesmetropole/photos_obliques
Cc : Bruel Gaetan; Mention
Objet : Re: [sigrennesmetropole/photos_obliques] Intégration dans l'architecture de georchestra version 16.12 (#1)


Bonjour, concernant les url d'accès aux ressources tout est décrit dans les chapitres 2.1 et 3.4 de nos spécifications.

La colonne répertoire = le noms des répertoires sur le système de fichiers accessibles soit par apache soit par la webapp Java.
La colonne url = l'url

[screenshot343]<https://cloud.githubusercontent.com/assets/6370443/20011843/3d4f6d96-a2ad-11e6-86f2-c8940108e646.png>

@Gaetanbru<https://github.com/Gaetanbru> quel est le souci ?

**Comment by catmorales** [comment]
> 3.4 des spécifications.

En effet après discussion avec les utilisateurs actuels les photos sont toutes stockées sans arborescence particulière hormis ce qui est indiqué dans les spécifications.
Par contre je ne sais pas encore dans quel système de fichiers elles seront stockées: /DATA ou point de montage  sur le serveur depuis un autre serveur, .... ceci doit être paramétrable.

**Comment by catmorales** [comment]
Installation à faire sur testgeorchestra.
@fvanderbiest , je pense commencer à déployer ce module dans le tomcat cadastre sur le serveur de test mardi 17 matin, par contre j'aurai sans doute besoin de votre intervention pour cette intégration qui nécessitera sans doute un point de montage vers un autre serveur pour accéder au stock de photos, un vhost dans apache pour l'accès de l'addon aux vignettes, aperçus et zip.
Ces interventions seront à prendre sur les heures de support.

**Comment by fvanderbiest** [comment]
> je pense commencer à déployer ce module dans le tomcat cadastre sur le serveur de test mardi 17 matin, par contre j'aurai sans doute besoin de votre intervention pour cette intégration

OK, toute l'équipe geOrchestra sera présente et pourra vous assister au besoin.

S'il y a des choses à puppetiser (du coup pour la durée de vie restante des serveurs), il faudra tenir à jour une liste des modifications à apporter au système. En attendant on pourra les faire en root sur test au besoin.

**Comment by catmorales** [comment]
Merci François .
Par contre, il y a eu un changement dans mon calendrier et vais plutôt le faire mercredi après-midi ...

**Comment by catmorales** [comment]
@fvanderbiest  j'ai mis le dépot dans /tmp/depots  mais ce répertoire arrive à saturation 99% . Où me conseille tu de déplacer les dépots ?

**Comment by catmorales** [comment]
.. sur testgeorchestra

**Comment by fvanderbiest** [comment]
dans votre home ?

**Comment by catmorales** [comment]
c'est le home de tomcat alors

**Comment by catmorales** [comment]
@fvanderbiest  je dois paramétrer le tomcat-cadastre afin que la module photo oblique  (partie webapp soit déployé là)
cf https://github.com/sigrennesmetropole/photos_obliques/tree/master/webapps

0 - je suppose qu'il n'est pas nécessaire de paramétrer le **connecteur** car il va utiliser celui qui existe pour le tomcat-cadastre et qui est défini  dans /srv/tomcat/cadastre/conf/connector-http-8480-cadastre.xml:
```
<!-- file managed by puppet -->
<Connector URIEncoding="UTF-8"
           port="8480"

           protocol="HTTP/1.1"
           connectionTimeout="20000"
           redirectPort="8443" />

```
Tu confirmes ?
1- Il  me faut paramétrer la **connexion à la base** qui est différente de celle de cadastrapp cf  /srv/tomcat/cadastre/conf/context.xml:
```
<Context>
 <WatchedResource>WEB-INF/web.xml</WatchedResource>

  <Resource name="jdbc/cadastrapp"  auth="Container" type="javax.sql.DataSource"
          driverClassName="org.postgresql.Driver"
          url="jdbc:postgresql://127.0.0.1:5432/cadastrapp_arcopole"
          username="cadastrapp" password="cadastrapp"
          validationQuery="select 1"
          maxActive="20" maxIdle="10" maxWait="-1"/>

</Context>
```
Je supppose qu'il suffit de rajouter à la suite:

<Resource name="jdbc/photooblique"
        auth="Container"
        type="javax.sql.DataSource"
        driverClassName="org.postgresql.Driver"
        url="jdbc:postgresql://postgis-bdu:5432/bdu"
        username="intranet"
        password="xxx"
        maxTotal="20"
        maxIdle="10"
        maxWaitMillis="-1"
        validationQuery="select 1"
/>
Tu confirmes ?Cela va t'il impacter puppet ?
Ensuite bien sûr redémarrage service.

 2- Paramétrage Apache RP et SP pour faire communiquer client et server:
cf https://github.com/sigrennesmetropole/photos_obliques/tree/master/webapps
je ne pense pas avoir les droits pour faire cela .
Pouvez vous vous en occuper et prendre sur l'assistance pour ce faire ? Merci 
3- De mon côté je vais créer le fichier de configuration dans le datadir de georchestra et charger l'addon dans mapfishapp sur la branche test de github.

**Comment by catmorales** [comment]
Une petite précision sur le point 2. 
Le besoin est le suivant:
* Il nous faut un point de montage entre un serveur chez nous contenant les photos (extrêmement volumineux à termes)  et le répertoire /var/www/georchestra/htdocs/photos/ tel que paramétré dans https://github.com/sigrennesmetropole/photos_obliques/blob/master/webapps/src/main/resources/photooblique.properties.
Ce point de montage doit être accessible  en lecture par le user tomcat.

* les ZIP avant envoi sont préparés dans le temp/folder qui doit lui être accessible en écriture à l'utilisateur  tomcat

**Comment by catmorales** [comment]
- [ ]ajout connexion à la base  --> je n'ai pas le droit :( permission denied pour modifier context.xml
```
<?xml version='1.0' encoding='utf-8'?>
<Context>
 <WatchedResource>WEB-INF/web.xml</WatchedResource>

  <Resource name="jdbc/cadastrapp"  auth="Container" type="javax.sql.DataSource"
          driverClassName="org.postgresql.Driver"
          url="jdbc:postgresql://127.0.0.1:5432/cadastrapp_arcopole"
          username="cadastrapp" password="cadastrapp"
          validationQuery="select 1"
          maxActive="20" maxIdle="10" maxWait="-1"/>

 <Resource name="jdbc/photooblique"  auth="Container" type="javax.sql.DataSource"
          driverClassName="org.postgresql.Driver"
          url="jdbc:postgresql://postgis-bdu:5432/bdu"
          username="intranet" password="intranet"
          validationQuery="select 1"
          maxActive="20" maxIdle="10" maxWait="-1"/>
</Context>

```

**Comment by pmauduit** [comment]
C'est changé sur intra-test, désolé pour la rétention du fichier

**Comment by catmorales** [comment]
Merci @pmauduit , c'est fait 

- [ ] modif context.xml

**Comment by catmorales** [comment]
- [ ] déployer le war  dans /srv/tomcat/cadastre/webapp 

- [ ] redémarrer le service

**Comment by catmorales** [comment]
- [ ] mise à jour de /etc/georchestra

- [ ] redémarrage service georchestra

**Comment by catmorales** [comment]
- [ ] configuration du proxy dans https://github.com/camptocamp/georchestra-rennes-configuration/blob/test/security-proxy/targets-mapping.properties#L16

- [ ] mise à jour du datadir sur le serveur

 
- [ ] redémarrage du tomcat-proxycas

**Comment by catmorales** [comment]
Il reste le 
- Apache à paramétrer
- le point de montage à faire  (je vais voir de mon côté depuis quel serveur et comment) en attendans, on pourrait mettrr quelques photos en test ici ?
- regarder si il est nécessaire de modifier le fichier beans.xml (je ne sais pas)

et peut être autre chose à faire ... Je vous laisse la main @fvanderbiest et @pmauduit

**Comment by catmorales** [comment]
@fjacon - merci de prendre sur le support pour réaliser ce paramétrage

**Comment by fjacon** [comment]
@catmorales quand en avez-vous besoin ?

**Comment by catmorales** [comment]
le plus tôt possible ;)

**Comment by catmorales** [comment]
d'ici fin de semaine au plus  tard afin de pouvoir vraiment tester

**Comment by fvanderbiest** [comment]
Ajout proxypass:
```
georchestra@testgeorchestra (rennes_georchestra/test):/var/www/georchestra/conf$ cat photooblique.conf 
RewriteRule ^/photooblique$ /photooblique/ [R]
ProxyPass /photooblique/ https://testgeorchestra.mutu.local:8443/photooblique/
<Location /photooblique/>
    ProxyPassReverse https://testgeorchestra.mutu.local:8443/photooblique/
    RequestHeader set X-Forwarded-Proto "https"
</Location>
```
Restart apache

**Comment by fvanderbiest** [comment]
PS: je n'aime pas beaucoup donner des détails sur votre infra sur un gestionnaire de tickets public ... le risque de fuite de mot de passe n'est pas à négliger.

**Comment by catmorales** [comment]
Je suis d'accord oups , je n'avais pas fait gaffe .. autant pour moi  . Pas terrible en effet  :(

**Comment by catmorales** [comment]
ok merci @fvanderbiest , c'est bon pour moi, le module fonctionne sur la PF de test :).
Je ferme ce ticket et en  rouvrirai un sur la PF privée pour le point de montage quand la DSI aura proposé une solution.
