### ISSUE TITLE
[Addon] choix de la commune dans la sélection attributaire

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/photos_obliques#10]
Une fois les ou la  commune choisie(s), la sortie de la liste de choix n'est pas intuitive: il faut cliquer dans la fenêtre  ailleurs pour que cette liste soit masquée

**Comment by pierrejego** [comment]
je viens de faire le test, mais le fonctionnement semble logique vu que l'on peut faire une sélection multiple. A voir avec Gaetan, (il est absent cette semaine)

**Comment by Gaetanbru** [comment]
Le composant utilisé est une extension basé sur la comboBox d'extjs 3.4. La comboBox Extjs comme ce composant ne propose pas d'action pour fermer la liste autrement que par ces deux actions : 
- un clic sur la flèche (aussi nommée trigger)
- un clic hors de la liste affichée sous le champ

Je vous envoie un mail afin d'organiser un point.

**Comment by catmorales** [comment]
Expliquer le fonctionnement dans le screen cast
