### ISSUE TITLE
[Addon] redimensionnement vertical de la fenêtre de sélection

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/photos_obliques#11]
Impossible de redimensionner verticalement la fenêtre de résultat de la recherche attributaire et de la recherche graphique:
![image](https://cloud.githubusercontent.com/assets/4659829/23261468/85d2dd70-f9d6-11e6-8af3-b83f98b267a4.png)

**Comment by Gaetanbru** [comment]
La fenêtre s'adapte automatiquement au nombre de résultat. Le problème provient de la relation entre la fenêtre et l'élément contenant la liste de résultat. Ce type de problème a été rencontré avec cadastrapp (récurent avec notre version Extjs). 

Je regarderai les solutions possibles.

**Comment by Gaetanbru** [comment]
Je viens de réaliser des modifications pour rendre redimensionnement possible. Cependant une zone vide peut peupler la fenêtre sous le résultat (voir image). Cette zone peut être cachée avec le redimensionnement manuel.

![image](https://cloud.githubusercontent.com/assets/16317988/23620811/91b7c7b6-0298-11e7-98ff-6c0d523caff7.png)

Cet espace est du au fait que la fenêtre n'adapte plus sa taille en fonction de la taille de la liste de résultat. Afin de rendre le redimensionnement de la fenêtre possible, la fenêtre à une taille indépendant de la taille de son contenu.

Autre point, la fenêtre entière de résultat est minimisable et non plus la liste contenant les résultats. Lorsque la liste est minimiser, elle n'arrive plus à retrouver une taille en adéquation avec le résultat d'une autre requête. On ne voit donc plus qu'une seule ligne et la barre de défilement pour lire les autres. A mon sens, cette correction est en adéquation avec les autres fenêtres de cadastrapp depuis l'issue #322. 

Validez-vous ces corrections ?

**Comment by catmorales** [comment]
POur moi c'est bon , j'attends le retour de @MaelREBOUX

**Comment by catmorales** [comment]
webapp et addon redéployés ce matin sur test

**Comment by catmorales** [comment]
vérification du redimensionnement ok pour moi
