### ISSUE TITLE
[Addon] Panier - Gérer le cas où les dates de prises de vues sont vides

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/photos_obliques#12]
![image](https://cloud.githubusercontent.com/assets/4659829/23261629/7854e782-f9d7-11e6-93e6-23243d7e4d98.png)

Le champ date_ de la table phototheque.photooblique_emprise peut être vide, même si le champ année est renseigné . 
Gérer ce cas. Je propose que l'on mettre l'année si la date est vide.
@MaelREBOUX une autre idée ?

**Comment by Gaetanbru** [comment]
J'ai réalisé une modification, l'infobulle ne propose que l'id si la date n'existe pas en base de données (champ vide). 

@MaelREBOUX la modification est-elle en base de données ou côté client ? Les utilisateurs ne risquent-ils pas de mélanger les informations si nous donnons deux dates sous le même labels sans les avertir ?

**Comment by catmorales** [comment]
Oui c'est vrai ton option est peut être plus cohérente.
