### ISSUE TITLE
[Addon] Mentions légales 

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/photos_obliques#13]
![image](https://cloud.githubusercontent.com/assets/4659829/23261695/d1f48b9e-f9d7-11e6-9df1-d9c1da07d4cd.png)
* Corriger fautes et modifier le texte 
 "Vous devez impérativement faire apparaître les mentions légales présente**s** dans le fichier texte joint à chaque photo téléchargée lors de son utilisation"
* Où est ce paramétrable ?

**Comment by catmorales** [comment]
vu c'est dans le manifest.json
https://github.com/sigrennesmetropole/photos_obliques/blob/master/addons/photos_obliques/manifest.json#L35
Je peux faire la correction si vous voulez ...

**Comment by catmorales** [comment]
j'ai essaye d'ajouter lesoptions suivantes dans le config.json de mon serveur de test  mais ça ne fonctionne pas:
```
"cartSize": 500,
		"cartNb" : 25,
		"limitByPage":8,
    		"adminMsgAlert":"Service à contacter : Service SIG - portail.sig@rennesmetropole.fr ",
		"downloadMsg":"Vous devez impérativement faire apparaître les mentions légales présentes dans le fichier texte joint à chaque photo téléchargée lors de son utilisation!",
```

**Comment by Gaetanbru** [comment]
Je viens de modifier la phrase dans le manifest.json, je regarde pour l'option "cartsize"

**Comment by Gaetanbru** [comment]
Est-ce possible de me mettre en copie ton config.json ?

**Comment by catmorales** [comment]
ok je te l'envoie par mail

**Comment by Gaetanbru** [comment]
Les autres options insérées dans le config.json sont-elles bien prises en compte ?

**Comment by catmorales** [comment]
oui puisqu'il tape sur les bons services wms

**Comment by catmorales** [comment]
voilà ce qu'il affiche:
![image](https://cloud.githubusercontent.com/assets/4659829/23265153/261bc0f0-f9e4-11e6-8583-7996491c347f.png)

**Comment by catmorales** [comment]
et par mesure de précaution j'ai redémarré le service tomcat georchestra au cas où ..

**Comment by catmorales** [comment]
ahh mais  après avoir ajouté des données dans le panier cela s'est mis à jour:
![image](https://cloud.githubusercontent.com/assets/4659829/23265325/962add90-f9e4-11e6-9ece-9e70d3ea46c6.png)

**Comment by catmorales** [comment]
et la modification du texte a bien été prise en compte , donc fausse alerte ! c'est bon !
![image](https://cloud.githubusercontent.com/assets/4659829/23265459/eac305a8-f9e4-11e6-8220-b98e80d95c4a.png)

**Comment by Gaetanbru** [comment]
Cet état est bien l'état par défaut quand aucune image n'est dans le panier. Comme tu l'as déjà constaté elle se modifie dès qu'une image est insérée dans le panier. 

![image](https://cloud.githubusercontent.com/assets/16317988/23265498/1f07b2b4-f9e5-11e6-9abd-f596557ebae0.png)

Je vais pousser les modifications du manifest.json sur la master. Je ferai une nouvelle branche une fois ces premières anomalies corrigées.

**Comment by catmorales** [comment]
Oui il faudra que l'on rédige  un manuel utilisateur  pour ne plus se poser de questions.
