### ISSUE TITLE
[Add on] Afficher le nombre de photos dans le panier

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/photos_obliques#15]

**Comment by pierrejego** [comment]
@catmorales  ?

**Comment by catmorales** [comment]
oui ?

**Comment by catmorales** [comment]
je précise, on aimerait voir écrit en haut de l'interface le nombre de photos présentes dans le panier:
![image](https://cloud.githubusercontent.com/assets/4659829/24195036/7cbfce46-0ef8-11e7-8d85-a92c8aa80c20.png)

**Comment by Gaetanbru** [comment]
C'est bien entendu réalisable, mais je ne pense pas pouvoir le faire dans l'immédiat.

**Comment by catmorales** [comment]
OK pas de souci cela n'a rien d'urgent, ce sera un plus quand tu pourras le faire .

**Comment by Gaetanbru** [comment]
Réouverture : mauvaise manipulation lors du "push to upstream".

**Comment by Gaetanbru** [comment]
En attente de retour sur les corrections.

**Comment by catmorales** [comment]
Nombre de photos du panier affichées:
![image](https://cloud.githubusercontent.com/assets/4659829/25752631/1ee454d4-31b9-11e7-8faf-1092c4c26551.png)
