### ISSUE TITLE
[Addon] Rendre paramétrable la visibilité de la couche fonctionnelle d'emprises

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/photos_obliques#16]
Comme pour cadastrapp , car cela est perturbant quand la couche saute . 
Et cela permet de vérifier si elle est bien chargée. cf #17

**Comment by Gaetanbru** [comment]
Tu veux dire qu'il serait bien de rendre visible ou non la couche parmi les couches disponibles ? (volet latéral droite) ? Si c'est cela, ce paramètre pourra être modifier via une option du manifest.json. du type "display_layer: true / false". Elle sera prise en compte à l'activation du module.

**Comment by catmorales** [comment]
oui c'est bien ça :)
