### ISSUE TITLE
[Addon]Le chargement d'un nouveau contexte rend l'addon inopérant

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/photos_obliques#17]
Si l'utilisateur après avoir chargé et utilisé l'outil photo-oblique,  charge un nouveau contexte (non pas ajouter mais charger), la couche fonctionnelle disparait (j'imagine car on ne la voit pas) et l'outil devient inutilisable.
Une fermeture des fenêtres et nouveau chargement de l'outil rétablit la situation.
--> Prévoir un message d'erreur dans ce cas, informant l'utilisateur qu'il doit recharger l'outil.

**Comment by catmorales** [comment]
peut être qu'une autre solution peut répondre à ce besoin ? cf https://github.com/georchestra/cadastrapp/pull/326

**Comment by Gaetanbru** [comment]
J'ai en déjà remonté ce problème sur le github GeOrchestra pour l'addon Annotation entre autre. Il y a un élément de résolution (#326 comme tu l'as indiqué) que l'on doit essayer dans le cadre d'un autre projet. Si ce correctif peut être reporté sur la 15.12, alors on l'appliquera.

**Comment by catmorales** [comment]
> peut être reporté sur la 15.12, alors on l'appliquera.

Pour info, nos PF ne sont plus en 15.12, nosu étions branchés sur master de georchestra depuis l'automne dernier et nous sommes en train de stabiliser  en 16.12.

**Comment by Gaetanbru** [comment]
Je viens de tester sous GeOrchestra 15.8 avec le module Annotation. Fonctionnel, je vais porter le correctif asap sur Photos obliques.

**Comment by Gaetanbru** [comment]
Besoin de  modifier le code georchestra pour lancer l'event "aftercontexterestore".

**Comment by Gaetanbru** [comment]
En attente de retour sur les corrections.

**Comment by catmorales** [comment]
Tu attends que j'ai déployé la dernière version sur nos PF en 16.12 ?

**Comment by Gaetanbru** [comment]
1 - Au rechargement de la carte ("charger" un nouveau contexte), il est impossible d'ouvrir la fenêtre de recherche attributaire si la fenêtre de recherche graphique était ouverte : 

MESSAGE : Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

2 - La couche d'emprise des géométries n'est toujours pas visible mais existe bien : problème ZIndex.

**Comment by Gaetanbru** [comment]
Concernant le message : Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Lors du passage de la recherche graphique à la recherche attributaire, il y a suppression de la couche "graphique" de l'objet "map" alors qu'elle n'a pas était ajoutée à l'objet "map".

**Comment by Gaetanbru** [comment]
En attente de retour concernant l'affichage des résultat au passage de la souris.

**Comment by catmorales** [comment]
Dernière version de l'addon redéployée à l'instant  et testé:
* affichage d'une sélection de photos --> l'emprise s'affiche bien au passage de la souris
* chargement d'un nouveau contexte (et pas ajout) en ayant laissé la fenêtre de sélection ouverte --> l'emprise s'affiche toujours dans la carte .

Donc c'est OK
