### ISSUE TITLE
[Addon] Trier la liste des communes  sur le nom 

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/photos_obliques#18]
![image](https://cloud.githubusercontent.com/assets/4659829/24146107/7dcf0bf4-0e34-11e7-9ada-0ba4316ff586.png)

**Comment by pierrejego** [comment]
Bonjour,
il va être compliqué de faire le sort côté client à cause de la librairie utilisée. Nous allons faire la modification côté serveur, et trié par ordre alphabétique du nom de la commune dans le service.

**Comment by catmorales** [comment]
Merci ce sera plus pratique !
