### ISSUE TITLE
Problème sur tooltip "Vider panier"

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/photos_obliques#19]
![screenshot622](https://cloud.githubusercontent.com/assets/6370443/24411139/606f1378-13d5-11e7-8868-d8d9c283f2e7.png)

Problème ce devrait être "Retirer la photo du panier"

**Comment by MaelREBOUX** [comment]
Peut-être cette ligne, sans certitude : https://github.com/sigrennesmetropole/photos_obliques/blob/f2cd615cd74782aa73f182a8ac12fb24f0aa7c09/addons/photos_obliques/manifest.json#L122

**Comment by Gaetanbru** [comment]
il faut en effet changer l'i18n ligne 122 : 
"photooblique.panier.bouton.retirerselection":"Vider le panier"

**Comment by MaelREBOUX** [comment]
Fait : https://github.com/sigrennesmetropole/photos_obliques/commit/8f03f553b7394bcc328979fe8e1d0d5ddb3afa60
