### ISSUE TITLE
Modifier le nom du fichier téléchargé

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/photos_obliques#20]
Actuellement le fichier zip téléchargé avec les photos et les mentions s'appelle `zipTest.zip`. Il nous faut le nommer avec un nom plus pertinent + horodatage de préférence .
Cela est-il paramétrable et si oui où ?

**Comment by catmorales** [comment]
j'ai l'impression que ça se passe ici:
https://github.com/sigrennesmetropole/photos_obliques/blob/master/webapps/src/main/java/org/georchestra/photooblique/service/ExportController.java#L62

**Comment by catmorales** [comment]
@pierrejego merci de me dire quand tu pourras le faire.

**Comment by catmorales** [comment]
Vu ce soir 
![image](https://cloud.githubusercontent.com/assets/4659829/25752756/841090c0-31b9-11e7-9a00-7a9023d90292.png)
A quoi correspond le nombre affiché ?

**Comment by pierrejego** [comment]
Le chiffre c'est le timestamp de la date de génération.

**Comment by catmorales** [comment]
OK merci
