### ISSUE TITLE
Panier - Affichage en double

### ISSUE THREAD

**Issue by Gaetanbru** [sigrennesmetropole/photos_obliques#21]
Ajouter de la 1ère image dans le panier, celle-ci est en double.
Après contrôle côté client, une seule image est bien ajoutée.
Dans le store, une seule image est présente.
En modifiant ensuite la taille des images, o na bien qu'une seule image.

**Observation : On a un bogue d'affichage.**

- Cause : Provient du rafraîchissement du dataview
- Elément de résolution : Forcer le rafraîchissement du dataview

**Comment by Gaetanbru** [comment]
Résolu en forçant le "refresh".
Modification à pousser.

**Comment by Gaetanbru** [comment]
En attente de retour sur les corrections.

**Comment by catmorales** [comment]
Addon et weba pp redéployées ce jour. Pas d'affichage en double pour moi dan s le panier:
![image](https://cloud.githubusercontent.com/assets/4659829/25752582/04d287e6-31b9-11e7-9ed4-12f73b35d23f.png)
