### ISSUE TITLE
Problème champ "Prestataire" + ordre des attributs

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/photos_obliques#25]
Une coquille qui est passée sous les radars : renommer le 2e attribut "Propriétaire" en "Prestataire".

En profiter pour modifier l'ordre :
1. id
2. date
3. Propriétaire
4. Prestataire
5. Taille

![image](https://cloud.githubusercontent.com/assets/6370443/26192357/9c19827e-3bb1-11e7-941f-906330a2ff06.png)

**Comment by Gaetanbru** [comment]
Modification faite : 
- Modification de l'ordre des colonnes
- Modification de l'i18n dans le manifest.json, il y avait une erreur de copier / coller

Est-il possible de créer un label pour les issues du type : "Livré" ou " Résolu" ou "A tester" ?
Ceci pour avoir une vision des issues qui ont été retouchées et qui attendent un retour de votre part avant fermeture.

**Comment by MaelREBOUX** [comment]
Bonne idée, je propose 
- dev en cours
- corrigé, à tester
- corrigé, testé, à déployer
- corrigé, testé, déployé

@catmorales  ?

**Comment by catmorales** [comment]
oui ça ma va. je les fais.

**Comment by catmorales** [comment]
déployé en test . pour moi c'est bon

**Comment by Gaetanbru** [comment]
Je vous laisse fermer l'issue si tout vous convient.
