### ISSUE TITLE
Vérifier requête GeoServer

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/photos_obliques#28]
Des utilisateurs remontent un comportement surprenant en fonction du dessin du polygone.
En gros : inersecte / englobe ?

Où est-ce dans le code ?

**Comment by Gaetanbru** [comment]
Voici le fonctionnement décrit par les spécifications V1.3 du Module photo obliques : 
_**- l’outil sélectionne toutes les emprises de photos contenant entièrement le polygone saisi (et pas l'inverse).**_

Pour la requête vers le geoserver, elle intègre un filtre CQL basé sur la relation spatial **CONTAINS** : 
> Returns true if the geometry a contains b

  ... où la géométrie a correspondant aux géométries de la couche et la géométrie b au polygone dessiné.

Vous trouverez le code [ici](https://github.com/sigrennesmetropole/photos_obliques/blob/master/addons/photos_obliques/js/searchWindow.js#L161).
 Vous trouverez les spécifications geoserver sur les filtres CQL [ici](http://docs.geoserver.org/stable/en/user/filter/function_reference.html#filter-function-reference).

**Comment by Gaetanbru** [comment]
Pensez-vous qu'il faut modifier ce fonctionnement ?

**Comment by catmorales** [comment]
Ce fonctionnement a été largement discuté et validé  avec Frédéric Chauvin lors de la rédaction du cahier des charges

**Comment by Gaetanbru** [comment]
@MaelREBOUX, as-tu un cas qui te donne un résultat non valide ? Je souhaiterai en effet savoir si c'est un bogue que nous n'avions pas détecté.

**Comment by MaelREBOUX** [comment]
J'attend que les collègues fournissent 1 ou 2 exemples pour reproduire.

**Comment by MaelREBOUX** [comment]
C'est vu. Tout est conforme.

En fait : certains utilisateurs font des polygones très grands dans l'idée : "comme ça j'aurais tout".
Sauf que c'est exactement l'inverse qu'il faut faire.

On ne change rien : on va modifier la documentation et le screencast.
