### ISSUE TITLE
[Installation webapp] Problème de type 

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/photos_obliques#6]
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [taille_fichier] in table [photooblique_emprise]; found [numeric (Types#NUMERIC)
], but expecting [int4 (Types#INTEGER)]

**Comment by pierrejego** [comment]
La colonne taille_fichier a été ajouté. Lors de nos échanges vous nous aviez indiquer quelle serait de type Integer, vous avez du la mettre en Numeric finalement.

Est-ce que vous changer le type de la colonne en base ou est-ce que je fais les modifications dans l'application ?

**Comment by catmorales** [comment]
Ok je boucle avec mon collègue en charge des bases de données et je te redis demain.

**Comment by catmorales** [comment]
Bon c'est corrigé en base on est passé sur de l'integer
