### ISSUE TITLE
[Installation] erreurs dans fichier beans.xml

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/photos_obliques#7]
* référence à cadastrapp :https://github.com/sigrennesmetropole/photos_obliques/blob/master/webapps/src/main/webapp/WEB-INF/beans.xml#L23

* mauvais nommage du fichier properties: https://github.com/sigrennesmetropole/photos_obliques/blob/master/webapps/src/main/webapp/WEB-INF/beans.xml#L28
 c'est photooblique.properties et non pas photoblique.properties

Pour info, je dois modifier ce fichier avant compilation ??? et redéployer le war ensuite n'est ce pas?

**Comment by pierrejego** [comment]
Bonjour,
oui c'est mieux pour les prochaines mises à jour. 
Mais tu peux aussi modifier directement le beans.xml dans le répertoire déployé dans le tomcat pour faire des tests.  
Quand tu sauvegarderas le fichier, l'application se rechargera pour prendre en compte les modifications.

Je m'occupe de la partie log dans l'après-midi, elles ne sont pas géreés dans le datadir pour l'instant.

**Comment by catmorales** [comment]
Bonjour,
Oui en effet j'ai des erreurs dans les logs,  car j'ai mis dans le datadir de georchestra le fichier logback.xml

**Comment by catmorales** [comment]
Bon j'ai corrigé dans le fichier sur le serveur: il y a moins d'erreurs.
Je suis maintenant en attente de la config apache par C2C.
