### ISSUE TITLE
[Taille fichier ] mauvais dimensionnement

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/photos_obliques#9]
Il n'y a pas de calcul de la taille des fichiers , l'application l'affiche en Mo mais prend les informations brutes dans la base.
 Or en base elles sont en Octets donc le calcul est mauvais:
![image](https://cloud.githubusercontent.com/assets/4659829/22832109/06dc16f4-efad-11e6-9bb2-657221f05ed8.png)

**Comment by pierrejego** [comment]
Effectivement, il n'y a aucune conversion pour l'instant, je vais le mettre en place. 
Dans les notes que j'ai, nous avions dit, affichage en Mo sans virgule. Est-ce que c'est bien ça que vous voulez ?

 Les données en base sont en octet ou en kilooctet ?

**Comment by MaelREBOUX** [comment]
Dans mes notes suite à l'échange du 01/12 j'avais noté qu'on stockait la taille en octets (valeur brute) et que l'application faisait une conversion en Mo (sans virgule) pour affichage à l'utilisateur.

L'avantage de stocker la valeur brute est pour nous d'en profiter pour faire un calcul fin de la taille totale de ces fichiers sur nos serveurs.

**Comment by pierrejego** [comment]
Parfait, merci. Je fais la modification dans l'après midi.

> J'ai prévu de m'occuper de remplir la table cette semaine. Au moins avec les tailles des aperçus dans un premier temps.
@MaelREBOUX je suis pas sur d'avoir compris mais ok
